### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by anjiro** [mikaelho/pythonista-uiconstraints#1]
Pythonista 3.6.1 on an iPad Pro with iOS 14.3. I installed anchor with the latest version of Stash. When I run anchor.py with Python 3.6, I get:

```
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/D0B1EFA6-D02E-494B-B7E7-B4E1F0434866/Pythonista3/Documents/site-packages-3/anchor.py", line 1423, in <module>
    root = LayoutDemo()
  File "/private/var/mobile/Containers/Shared/AppGroup/D0B1EFA6-D02E-494B-B7E7-B4E1F0434866/Pythonista3/Documents/site-packages-3/anchor.py", line 1327, in __init__
    self.create_ui()
  File "/private/var/mobile/Containers/Shared/AppGroup/D0B1EFA6-D02E-494B-B7E7-B4E1F0434866/Pythonista3/Documents/site-packages-3/anchor.py", line 1375, in create_ui
    main_frame.add_subview(search_button)
TypeError: Expected a View

```

**Comment by mikaelho** [comment]
Hi Daniel, the latest and maintained versions of anchors are in the ui3 package. Excellent if you could try that instead (pip install ui3).

But if you absolutely need this version, I can take a look at what has changed.

**Comment by anjiro** [comment]
Aah, I didn't know about ui3. I might suggest adding a note in the anchor Readme pointing to it 🙂

**Comment by mikaelho** [comment]
👍🏻 Have been meaning to do it.
